apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: "dev"
  labels:
    app: or-frontend-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 32000
  selector:
    app: or-frontend-app